src/app/components/students/expelled-students/expelled-students.component.html
src/app/components/students/expelled-students/expelled-students.component.scss
src/app/components/students/expelled-students/expelled-students.component.ts
src/app/components/students/renew-student/renew-student.component.html
src/app/components/students/renew-student/renew-student.component.scss
src/app/components/students/renew-student/renew-student.component.spec.ts
src/app/components/students/renew-student/renew-student.component.ts
src/app/components/students/stop-academic-vacation/stop-academic-vacation.component.html
src/app/components/students/stop-academic-vacation/stop-academic-vacation.component.scss
src/app/components/students/stop-academic-vacation/stop-academic-vacation.component.spec.ts
src/app/components/students/stop-academic-vacation/stop-academic-vacation.component.ts
src/app/components/students/students-in-vacation/students-in-vacation.component.html
src/app/components/students/students-in-vacation/students-in-vacation.component.scss
src/app/components/students/students-in-vacation/students-in-vacation.component.ts
src/app/components/students/students.component.html
src/app/components/students/students.module.ts
src/app/services/general.service.ts
src/app/services/student.service.ts

Renew expelled students and stop academic vacations

---

src/app/components/grade/grade.component.html
src/app/components/grade/grade.component.ts
src/app/components/grade/grade.module.ts
src/app/components/grade/grades-panel/grades-panel.component.html
src/app/components/grade/grades-panel/grades-panel.component.scss
src/app/components/grade/grades-table/grades-table.component.html
src/app/components/grade/grades-table/grades-table.component.scss
src/app/components/grade/grades-table/grades-table.component.ts

Виправлення зауважень що виникли на репетиції демо

Adding comments

---

src/app/components/app/app.component.html
src/app/components/app/app.component.ts
src/app/components/app/header/header.component.ts
src/app/routes/routes.ts

Page title

---

src/app/components/app/app.component.ts
src/app/components/app/app.module.ts
src/app/components/app/header/header.component.html
src/app/components/specialization/specialization.component.html
src/app/components/specialization/specialization.component.scss
src/app/components/specialization/specialization.component.spec.ts
src/app/components/specialization/specialization.component.ts
src/app/components/specialization/specialization.module.ts
src/app/components/specialization/specializations-table/specializations-table.component.html
src/app/components/specialization/specializations-table/specializations-table.component.scss
src/app/components/specialization/specializations-table/specializations-table.component.spec.ts
src/app/components/specialization/specializations-table/specializations-table.component.ts
src/app/models/Specialization.ts
src/app/routes/routes.ts
src/app/services/specialization.service.spec.ts
src/app/services/specialization.service.ts

Issue #42 
Changelist:
- Added module, service, component and table-component for specializations.
- Show all active or not active specializations
- Select rows in table
PS Не удалось только зафиксировать заголовок таблицы

Show specializations

---

src/app/components/app/app.module.ts
src/app/components/specialization/add-specialization/add-specialization.component.html
src/app/components/specialization/add-specialization/add-specialization.component.scss
src/app/components/specialization/add-specialization/add-specialization.component.spec.ts
src/app/components/specialization/add-specialization/add-specialization.component.ts
src/app/components/specialization/specialization.component.html
src/app/components/specialization/specialization.component.scss
src/app/components/specialization/specialization.component.ts
src/app/components/specialization/specialization.module.ts
src/app/models/Specialization.ts
src/app/services/department.service.spec.ts
src/app/services/department.service.ts
src/app/services/specialization.service.ts
src/styles.scss

Issue #81 
Added form for creating new specialization

Add specializations

---

src/app/components/app/app.component.ts
src/app/components/app/header/header.component.html
src/app/components/specialization/add-specialization/add-specialization.component.html
src/app/components/specialization/pipes/search-specializations.pipe.spec.ts
src/app/components/specialization/pipes/search-specializations.pipe.ts
src/app/components/specialization/specialization-form/specialization-form.component.html
src/app/components/specialization/specialization-form/specialization-form.component.ts
src/app/components/specialization/specialization-modal/specialization-modal.component.html
src/app/components/specialization/specialization-modal/specialization-modal.component.ts
src/app/components/specialization/specialization.component.html
src/app/components/specialization/specialization.component.scss
src/app/components/specialization/specialization.component.ts
src/app/components/specialization/specialization.module.ts
src/app/components/specialization/specializations-table/specializations-table.component.html
src/app/components/specialization/specializations-table/specializations-table.component.scss
src/app/components/specialization/update-specialization/update-specialization.component.html

Added search by name for specializations
Deleted validation for some field in specialization`s form
Refactored page`s title

Specialization fixes & search

---

package-lock.json
package.json
src/app/components/students/add-student/add-student.component.html
src/app/components/students/renew-student/renew-student.component.html
src/app/components/students/renew-student/renew-student.component.ts
src/app/components/students/stop-academic-vacation/stop-academic-vacation.component.html
src/app/components/students/stop-academic-vacation/stop-academic-vacation.component.ts
src/app/components/students/student-academic-vacation/student-academic-vacation.component.html
src/app/components/students/student-degree-info/student-degree-info.component.html
src/app/components/students/student-degree-info/student-degree-info.component.scss
src/app/components/students/student-degree-info/student-degree-info.component.ts
src/app/components/students/student-expel/student-expel.component.html
src/app/components/students/student-personal-info/student-personal-info.component.html
src/app/components/students/student-personal-info/student-personal-info.component.scss
src/app/components/students/student-personal-info/student-personal-info.component.ts
src/app/components/students/student-typeahead/student-typeahead.component.html
src/app/components/students/students-table/students-table.component.html
src/app/components/students/students-table/students-table.component.ts
src/app/components/students/students.component.scss
src/app/models/Student.ts
src/app/services/student.service.ts

- added orderDate and orderNumber fields for renew student forms
- added "*" to required form fields
- fixed students page layout when browser zoom is changed
- hide photo upload in student personal info form (will be fixed later)
- fixed errors in degree info form
- fixed date format in tables

Students fixes

---

src/app/components/specialization/specialization-form/specialization-competencies/specialization-competencies.component.html
src/app/components/specialization/specialization-form/specialization-competencies/specialization-competencies.component.scss
src/app/components/specialization/specialization-form/specialization-competencies/specialization-competencies.component.spec.ts
src/app/components/specialization/specialization-form/specialization-competencies/specialization-competencies.component.ts
src/app/components/specialization/specialization-form/specialization-form.component.html
src/app/components/specialization/specialization-form/specialization-form.component.scss
src/app/components/specialization/specialization-form/specialization-form.component.ts
src/app/components/specialization/specialization.module.ts
src/app/components/specialization/update-specialization/update-specialization.component.html
src/app/components/specialization/update-specialization/update-specialization.component.ts
src/app/models/AcquiredCompetencies.ts
src/app/models/Specialization.ts
src/app/services/specialization.service.ts

- Deleted unused fields.
- Added certificate date and number
- Added competencies`s tab (only for update)

Update specialization form

---

src/app/components/app/app.module.ts
src/app/components/shared/httpErrors.ts
src/app/components/specialization/specialization-form/enums/lang.enum.ts
src/app/components/specialization/specialization-form/services/acquired-competencies.service.spec.ts
src/app/components/specialization/specialization-form/services/acquired-competencies.service.ts
src/app/components/specialization/specialization-form/specialization-competencies/specialization-competencies.component.ts
src/app/components/specialization/specialization-form/specialization-form.component.html
src/app/components/specialization/specialization-form/specialization-form.component.ts
src/app/components/specialization/specialization.module.ts
src/app/services/degree.service.ts
src/app/services/department.service.ts
src/app/services/grade.service.ts
src/app/services/group.service.ts
src/app/services/specialization.service.ts

- Editing competencies for both language
- Reject editing if competencies doesn't exist
- Refactored handle error function for promise

Edit competencies

---

src/app/components/students/assign-record-book-number-to-students/assign-record-book-number-to-students.component.html
src/app/components/students/assign-record-book-number-to-students/assign-record-book-number-to-students.component.scss
src/app/components/students/assign-record-book-number-to-students/assign-record-book-number-to-students.component.spec.ts
src/app/components/students/assign-record-book-number-to-students/assign-record-book-number-to-students.component.ts
src/app/components/students/students.component.html
src/app/components/students/students.module.ts
src/app/services/student.service.ts

Assigning record book numbers to students #157

---

src/app/components/specialization/specialization-form/specialization-form.component.html
src/app/components/specialization/specialization-form/specialization-form.component.ts
src/app/models/Specialization.ts

close #171 
related chdtu-fitis/deanoffice-backend#189

Add specialization code field to add/edit dialogs

---

src/app/components/courses-for-groups/courses-for-groups.component.ts
src/app/services/group.service.ts

Worker of foreign faculty can get course for group from all faculty

---

src/app/components/specialization/specialization-form/specialization-form.component.html
src/app/components/specialization/specialization-form/specialization-form.component.scss
src/app/components/specialization/specialization-form/specialization-form.component.ts
src/app/services/speciality.service.ts

close #172 
related chdtu-fitis/deanoffice-backend#193

Worker can get speciality that not used in this faculty before 

---

src/app/services/speciality.service.ts

close #179
close chdtu-fitis/deanoffice-backend#196

getSpecialities method now return only active speciality (#179)

---

src/app/components/students/constants.ts
src/app/components/students/expelled-students/expelled-students.component.html
src/app/components/students/expelled-students/expelled-students.component.ts
src/app/components/students/student-degree-info/student-degree-info.component.ts

enhancement: student-degree-info: allow edit only user faculty

---

src/app/components/shared/utils.ts
src/app/components/students/constants.ts

Ag grid date format

---

src/app/components/students/expelled-students/expelled-students.component.html
src/app/components/students/expelled-students/expelled-students.component.ts
src/app/components/students/student-all-info/student-all-info.component.ts

Працівник деканату може поновити студента, що був відрахований давно, після знаходження його засобами пошуку у відрахованих    
Поставити дату початку пошуку за замовчуванням семирічної давнини
В навчальних даних студента показується одна група для всіх студентів - перша на факультеті

expelled-students enhancement and fix

---

src/app/components/courses-for-groups/courses-for-groups.component.scss
src/app/components/courses-for-groups/courses-for-groups.component.ts

courses-for-groups bugfix

---

src/app/components/courses-for-groups/courses-for-groups.component.html
src/app/components/courses-for-groups/courses-for-groups.component.scss
src/app/components/courses-for-groups/courses-for-groups.component.ts
src/app/services/course.service.ts

216 feat/hours per credits in courses for groups

---

src/app/components/reports/debtors-statistics/debtor-statistics.component.html

#238: fix: debtor statistics columns exchange

---

src/app/components/courses-for-groups/courses-for-groups.component.html
src/app/components/courses-for-groups/courses-for-groups.component.scss

240 fix/elements position in header

---

src/app/components/courses-for-groups/course-creation/course-creation.component.html
src/app/components/courses-for-groups/course-creation/course-creation.component.ts
src/app/components/courses-for-groups/courses-for-groups.component.html
src/app/components/courses-for-groups/courses-for-groups.component.ts
src/app/components/courses-for-groups/edit-dialog/edit-dialog.component.html
src/app/models/Course.ts
src/app/services/course.service.ts

Close #234 
Close #233 
Fix #237

#234 course-creation: fix: same course creation

---

src/app/components/grade/grade.component.html
src/app/components/grade/grade.component.ts
src/app/components/grade/grade.module.ts
src/app/components/grade/grades-table/grades-table.component.html
src/app/components/grade/grades-table/grades-table.component.scss
src/app/components/grade/grades-table/grades-table.component.ts
src/app/components/grade/models/PostGrade.ts
src/app/services/grade.service.ts

Add default parameter
add legend for understanding color meaning

#280: on time for grades: add: ability to change on time property

---

src/app/components/reports/debtors-statistics/debtor-statistics.component.ts
src/app/components/shared/utils.ts
src/app/components/students/edebo-diploma-number/edebo-diploma-number.component.html
src/app/components/students/edebo-diploma-number/edebo-diploma-number.component.scss
src/app/components/students/edebo-diploma-number/edebo-diploma-number.component.ts
src/app/models/basemodels/Person.ts
src/app/models/edebo-diploma-number/DiplomaAndSynchronizedStudentDTO.ts
src/app/models/edebo-diploma-number/DiplomaNumberForSaveDTO.ts
src/app/services/edebo-diploma-number.service.ts

Виніс метод для отримання поточного сезону з компоненту debtors-statistics в utils
Виніс логіку, що створювала об'єкти перед відправленням з компоненту в конструктор класу
Багато змін в HTML файлі тому, що там була не семантична верстка (таблиця в формі)
Підправив стилі https://csswizardry.com/2011/09/writing-efficient-css-selectors/

297 enhance/set dates diploma number synchronization

---

src/app/components/grade/grades-table/grades-table.component.html
src/app/components/grade/grades-table/grades-table.component.ts

303 enhance/handle arrow keys

---

package-lock.json
package.json
src/app/components/app/app.module.ts
src/app/components/courses-for-groups/course-creation/course-creation.component.ts
src/app/components/courses-for-groups/courses-for-groups.component.html
src/app/components/courses-for-groups/courses-for-groups.component.ts
src/app/components/courses-for-groups/courses-for-groups.module.ts
src/app/components/department/department.component.ts
src/app/components/department/department.module.ts
src/app/components/group/delete-group/delete-group.component.ts
src/app/components/group/group.component.html
src/app/components/group/group.component.ts
src/app/components/group/group.module.ts
src/app/components/group/recovery-group/recovery-group.component.ts
src/app/components/shared/alerts/alert-options.ts
src/app/components/shared/alerts/alerts-config.ts
src/app/components/shared/alerts/alerts.module.ts
src/app/components/shared/alerts/alerts.service.ts
src/app/components/shared/alerts/models/alert-options.ts
src/app/components/shared/alerts/models/toastr-adapter.ts
src/app/components/shared/utils.ts
src/app/components/teachers/teachers.component.html
src/app/components/teachers/teachers.module.ts
src/styles.scss

Підправив в деяких місцях текстовки, бо вони були не дуже зрозумілими

Rewrite notifications
